### ISSUE TITLE
Include Compass Credo plugin to Elixir template

### ISSUE THREAD

**Issue by hanam1ni** [nimblehq/compass-credo-plugin#6]
## Why

We need to include this plugin in the Elixir template for the future Elixir project.

## Acceptance criteria

When project is generate from Elixir template, it should have the plugin in the project dependency and enable by default

**Comment by byhbt** [comment]
hi @hanam1ni !

I created an issue on the ElixirTemplate repository here: https://github.com/nimblehq/elixir-templates/issues/277. So when you integrate this plugin in the Template please attach it to the PR. It helps us to document the integration in the template release. Thank you!

**Comment by byhbt** [comment]
https://github.com/nimblehq/elixir-templates/issues/277 is merged. So we can mark this issue as Done
